/*
 * (c) (2022-2023), Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees.
 *
 * \warning   Autogenerated file. Do not edit!
 * generated on: 2026.03.04. 15:07
 * generated from interface specification revision: f00fa7c1
 * generated for CTRX firmware revision: 1.0.0-qsr.rc1
 * generated with metalib release 1.2.0.beta
 * generated with metagen version 0.8.0.0
 */

#ifndef IFXRFE_FIRMWARECOMMANDS_SERDES_H_8188
#define IFXRFE_FIRMWARECOMMANDS_SERDES_H_8188 1

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "8188/IfxRfe_CtrxCommandParams.h"
#include "IfxRfe_ErrorDefinitions.h"
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
namespace IfxRfe_Ctrx8188
{
#endif

    /******************************************************************************/
    /*--------------------------------Type definitions----------------------------*/
    /******************************************************************************/

    /******************************************************************************/
    /*---------------------------Function Declarations----------------------------*/
    /******************************************************************************/
    /// \brief Write memory range of a specified region after verifying passkey as needed - serializer
    /// \note For internal use only
    /// \param region Region of memory to be written.
    /// \param length Number of data words to be written
    /// \param passkey Passkey to access given addresses
    /// \param start_addr Relative start address in the region to write Data Words
    /// \param data_word Data words to be written
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    /// \retval IFXRFE_E_MISSING_PARAMETER if array is NULL and length greater 0
    error_t _writeMemorySerialize(uint8_t region, uint8_t length, uint32_t passkey, uint32_t start_addr, const uint32_t *data_word, uint32_t *payload, uint8_t *payload_length);

    /// \brief Reads data words from a set of addresses. - serializer
    /// \note For internal use only
    /// \param region Region of memory to read from
    /// \param length Number of data words to be read
    /// \param passkey Passkey to access given addresses
    /// \param from_addr Relative start address in the region to read the data words
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _readMemorySerialize(uint8_t region, uint8_t length, uint32_t passkey, uint32_t from_addr, uint32_t *payload, uint8_t *payload_length);

    /// \brief Reads data words from a set of addresses. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _readMemoryParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_readMemoryResult_t *res);

    /// \brief Download a given block of RAM Firmware - serializer
    /// \note For internal use only
    /// \param key1 Key1 value of the block to be downloaded.
    /// \param length Number of code words in the block.
    /// \param key2 Key2 value of the block to be downloaded.
    /// \param key3 Key3 value of the block to be downloaded.
    /// \param code_word Code words of the block
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    /// \retval IFXRFE_E_MISSING_PARAMETER if array is NULL and length greater 0
    error_t _downloadFwFunctionsSerialize(uint8_t key1, uint8_t length, uint32_t key2, uint32_t key3, const uint32_t *code_word, uint32_t *payload, uint8_t *payload_length);

    /// \brief Change of initialization settings - serializer
    /// \note For internal use only
    /// \param length Number of settings to be changed
    /// \param iram_descriptor Specifies which setting to be changed
    /// \param value New value of the setting
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    /// \retval IFXRFE_E_MISSING_PARAMETER if array is NULL and length greater 0
    error_t _initializeSerialize(uint8_t length, const uint32_t *iram_descriptor, const uint32_t *value, uint32_t *payload, uint8_t *payload_length);

    /// \brief Performs the warm-up calibration of the MMIC - serializer
    /// \note For internal use only
    /// \param calib_sub_func_id Flags for the calibrations to be performed:
    /// \param tx_ch_pow_idx If bit is set, perform the power calibration for the selected power index of the selected TX channel.
    /// \param ref_temp_idx Reference temperature index to decide if calibration should be executed (0 = no reference temperature).
    /// \param limit_temp Temperature difference limit to avoid recalibration if actual temperature difference is less than this limit (in Q12.3 format).
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _executeCalibrationSerialize(uint16_t calib_sub_func_id, uint32_t tx_ch_pow_idx, uint16_t ref_temp_idx, uint16_t limit_temp, uint32_t *payload, uint8_t *payload_length);

    /// \brief Performs the warm-up calibration of the MMIC - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _executeCalibrationParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_executeCalibrationResult_t *res);

    /// \brief Configure DMUX pins signal routing and direction. - serializer
    /// \note For internal use only
    /// \param config_mask b0 = 1 Valid DMUX1 configuration
    /// \param dmux1_alt_signal Digital signal routed through the DMUX pin (for input, set to 0h).
    /// \param dmux1_dir DMUX pin direction input/output
    /// \param dmux1_pulse_duration_ext Optional output pulse duration extension (for input, set to 0h).
    /// \param dmux2_alt_signal see DMUX1 description
    /// \param dmux2_dir see DMUX1 description
    /// \param dmux2_pulse_duration_ext see DMUX1 description
    /// \param dmux3_alt_signal see DMUX1 description
    /// \param dmux3_dir see DMUX1 description
    /// \param dmux3_pulse_duration_ext see DMUX1 description
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _configureDmuxSerialize(uint8_t config_mask, uint8_t dmux1_alt_signal, uint8_t dmux1_dir, uint8_t dmux1_pulse_duration_ext, uint8_t dmux2_alt_signal, uint8_t dmux2_dir, uint8_t dmux2_pulse_duration_ext, uint8_t dmux3_alt_signal, uint8_t dmux3_dir, uint8_t dmux3_pulse_duration_ext, uint32_t *payload, uint8_t *payload_length);

    /// \brief Configure the sequencer for a ramp scenario based on the sequencer setup structure stored in memory. - serializer
    /// \note For internal use only
    /// \param startoffset Relative address in the sequencer memory from where to read the sequencer configuration.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _configureRampScenarioSerialize(uint16_t startoffset, uint32_t *payload, uint8_t *payload_length);

    /// \brief Start a preconfigured ramp scenario - serializer
    /// \note For internal use only
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _startRampScenarioSerialize(uint32_t *payload, uint8_t *payload_length);

    /// \brief Wait for sequencer to complete the sequencer program and, after this, drive the device into the Operation state. - serializer
    /// \note For internal use only
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _finishRampScenarioSerialize(uint32_t *payload, uint8_t *payload_length);

    /// \brief Wait for sequencer to complete the sequencer program and, after this, drive the device into the Operation state. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _finishRampScenarioParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_finishRampScenarioResult_t *res);

    /// \brief Read a stored result from a given result area. - serializer
    /// \note For internal use only
    /// \param interface Interface for returning the results
    /// \param length Number of data words to read.
    /// \param offset Word offset within result to read from.
    /// \param res_identifier Identifies a result.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _getResultsSerialize(uint8_t interface, uint16_t length, uint16_t offset, uint32_t res_identifier, uint32_t *payload, uint8_t *payload_length);

    /// \brief Read a stored result from a given result area. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _getResultsParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_getResultsResult_t *res);

    /// \brief Clear requested result areas. - serializer
    /// \note For internal use only
    /// \param clr_areas_msk Bitmask indicating which areas are to be cleared.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _clearResultsSerialize(uint8_t clr_areas_msk, uint32_t *payload, uint8_t *payload_length);

    /// \brief Go to Low Power State - serializer
    /// \note For internal use only
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _gotoLowPowerSerialize(uint32_t *payload, uint8_t *payload_length);

    /// \brief Read the temperature from all the DTSs. - serializer
    /// \note For internal use only
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _getTemperatureSerialize(uint32_t *payload, uint8_t *payload_length);

    /// \brief Read the temperature from all the DTSs. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _getTemperatureParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_getTemperatureResult_t *res);

    /// \brief Measure the transmitted power (and possibly phase) of the Transmitter channels. - serializer
    /// \note For internal use only
    /// \param mode Mode of measurement
    /// \param ch_mask Transmitter channel to be measured:
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _measureTxSerialize(uint8_t mode, uint8_t ch_mask, uint32_t *payload, uint8_t *payload_length);

    /// \brief Measure the transmitted power (and possibly phase) of the Transmitter channels. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _measureTxParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_measureTxResult_t *res);

    /// \brief Execute the monitoring routines - serializer
    /// \note For internal use only
    /// \param detail_result Flag for enabling the writing of the monitoring result in the respective result area.
    /// \param monitoring_sub_func_id Flags for the monitoring functions to be performed.
    /// \param nmod TX modulator (DPLL) static frequency during monitoring.
    /// \param tx_ch_mask Flags to specify on which TX channels to run the monitoring on.
    /// \param hp_sel RX Chain HP corner frequency selection for BB Monitoring.
    /// \param pl_tx Power level Index of the specified channel. Ignored if corresponding channel bit is not set in Channel Mask.
    /// \param phase_tx Phase index of the specified channel. Ignored if corresponding channel bit is not set in Channel Mask.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    /// \retval IFXRFE_E_MISSING_PARAMETER if fixed-length array pointer is NULL
    error_t _executeMonitoringSerialize(uint8_t detail_result, uint16_t monitoring_sub_func_id, uint32_t nmod, uint8_t tx_ch_mask, uint8_t hp_sel, const uint8_t pl_tx[8], const uint16_t phase_tx[8], uint32_t *payload, uint8_t *payload_length);

    /// \brief Execute the monitoring routines - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _executeMonitoringParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_executeMonitoringResult_t *res);

    /// \brief Calculate CRC of Memory Range. - serializer
    /// \note For internal use only
    /// \param region Region of memory to calculate CRC from.
    /// \param passkey Passkey to access given addresses
    /// \param from_addr Relative start address in the region to calculate CRC (word aligned).
    /// \param length Number of data words to calculate CRC.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _calculateMemoryCrcSerialize(uint8_t region, uint32_t passkey, uint32_t from_addr, uint32_t length, uint32_t *payload, uint8_t *payload_length);

    /// \brief Calculate CRC of Memory Range. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _calculateMemoryCrcParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_calculateMemoryCrcResult_t *res);

    /// \brief Change the DPLL's target frequency. It does not turn on the PAs automatically. - serializer
    /// \note For internal use only
    /// \param bc Switch to select whether band should be changed
    /// \param nmod NMOD (in Q5.20 format) is a parameter for TX modulator (DPLL) static frequency configuration.
    /// \param ncw NCW (in UQ9.20 format) is the new value for the upper band limit
    /// \param rampbw RAMPBW (in UQ5.20 format) is the new value for the bandwidth
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _configureRfFrequencySerialize(uint8_t bc, uint32_t nmod, uint32_t ncw, uint32_t rampbw, uint32_t *payload, uint8_t *payload_length);

    /// \brief Configure MMIC Clocks. - serializer
    /// \note For internal use only
    /// \param clock_selection Clock configuration flags (0b to disable, 1b to enable).
    /// \param clkout_source_resistance CLKOUT source resistance selection.
    /// \param clkout_bias_voltage CLKOUT load bias voltage selection.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _configureMmicClockSerialize(uint8_t clock_selection, uint8_t clkout_source_resistance, uint8_t clkout_bias_voltage, uint32_t *payload, uint8_t *payload_length);

    /// \brief Store up to 4 power levels along with power configuration timing for each transmitter channel. - serializer
    /// \note For internal use only
    /// \param action_mask Configuration action for the selected channels:
    /// \param ch_mask Flags to specify which channels to configure.
    /// \param tx_pa_slope_scale_fact PA Slope scaling factor of TX, 2^-8..5.0 in UQ8.8 format for TX.
    /// \param plvl Power back-off level of TX, 0..20[dB] in Q8.7 format.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    /// \retval IFXRFE_E_MISSING_PARAMETER if fixed-length array pointer is NULL
    error_t _configureTxPowerSerialize(uint8_t action_mask, uint8_t ch_mask, uint16_t tx_pa_slope_scale_fact, const uint16_t plvl[4], uint32_t *payload, uint8_t *payload_length);

    /// \brief Enable or disable transmitter to transmit the RF signal. - serializer
    /// \note For internal use only
    /// \param ch_mask Flags to specify on which channels to perform the action.
    /// \param action_mask Action to be performed for the selected channels.
    /// \param pl_tx Power level Index of the specified channel. Ignored if corresponding channel bit is not set in Channel Mask.
    /// \param phase_tx Phase index of the specified channel. Ignored if corresponding channel bit is not set in Channel Mask.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    /// \retval IFXRFE_E_MISSING_PARAMETER if fixed-length array pointer is NULL
    error_t _setTxOutputSerialize(uint8_t ch_mask, uint8_t action_mask, const uint8_t pl_tx[8], const uint16_t phase_tx[8], uint32_t *payload, uint8_t *payload_length);

    /// \brief Configure the receivers. - serializer
    /// \note For internal use only
    /// \param data_width_sel RX Chain Data width selection
    /// \param gain_sel RX Chain gain selection.Used to apply a calibrated gain configuration at TIA, LPF, DFE and PF
    /// \param data_rate_sel HSRIF data rate selection for CSI2 operation
    /// \param start_mode HSRIF start mode for CSI2 operation
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _configureRxSerialize(uint8_t data_width_sel, uint8_t gain_sel, uint8_t data_rate_sel, uint8_t start_mode, uint32_t *payload, uint8_t *payload_length);

    /// \brief Enable the clock input. - serializer
    /// \note For internal use only
    /// \param action_mask Actions which should be performed.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _setMmicClockSerialize(uint8_t action_mask, uint32_t *payload, uint8_t *payload_length);

    /// \brief Return the MMIC version information. - serializer
    /// \note For internal use only
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _getVersionSerialize(uint32_t *payload, uint8_t *payload_length);

    /// \brief Return the MMIC version information. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _getVersionParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_getVersionResult_t *res);

    /// \brief Go to Operation State - serializer
    /// \note For internal use only
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _gotoOperationSerialize(uint32_t *payload, uint8_t *payload_length);

    /// \brief Enable/Disable clock MCU and/or clock PHY output. Command is valid only after switching to external clock derived from XIN. - serializer
    /// \note For internal use only
    /// \param clkmcu_action Enable/Disable the CLKMCU output
    /// \param clkmcu_freq Clock MCU output frequency
    /// \param clkphy_action Enable/Disable the CLKPHY output
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _setClockOutputSerialize(uint8_t clkmcu_action, uint8_t clkmcu_freq, uint8_t clkphy_action, uint32_t *payload, uint8_t *payload_length);

    /// \brief Return the MMC's current status - serializer
    /// \note For internal use only
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _getStatusSerialize(uint32_t *payload, uint8_t *payload_length);

    /// \brief Return the MMC's current status - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _getStatusParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_getStatusResult_t *res);

    /// \brief Exit of pre_operation state and go to Low power state - serializer
    /// \note For internal use only
    /// \param rom_fw_ver Version of ROM Firmware for confirmation.
    /// \param ram_fw_ver Version of the currently running Firmware for confirmation.
    /// \param auth_data Firmware authentication data to allow transition into Low power state.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _exitPreOperationSerialize(uint32_t rom_fw_ver, uint32_t ram_fw_ver, uint32_t auth_data, uint32_t *payload, uint8_t *payload_length);

    /// \brief Read and optionally clear error flags. - serializer
    /// \note For internal use only
    /// \param action Action to be performed
    /// \param error_mask_1 Error word mask to specify which error of Error Status 1 shall be cleared.
    /// \param error_mask_1_present Flag to indicate whether the field error_mask_1 should be serialized
    /// \param length Number of words in error_mask_2
    /// \param error_mask_2 Error word mask to specify which error of Error Status 2 shall be cleared.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    /// \retval IFXRFE_E_MISSING_PARAMETER if array is NULL and length greater 0
    error_t _handleErrorSerialize(uint8_t action, uint16_t error_mask_1, bool error_mask_1_present, uint8_t length, const uint32_t *error_mask_2, uint32_t *payload, uint8_t *payload_length);

    /// \brief Read and optionally clear error flags. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _handleErrorParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_handleErrorResult_t *res);

    /// \brief Return the RX transfer function parameters. - serializer
    /// \note For internal use only
    /// \param hp HP corner frequency.
    /// \param gain_sel RX Chain gain selection.Used to apply a calibrated gain configuration at TIA, LPF, DFE and PF
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _getRxTfParametersSerialize(uint8_t hp, uint8_t gain_sel, uint32_t *payload, uint8_t *payload_length);

    /// \brief Return the RX transfer function parameters. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _getRxTfParametersParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_getRxTfParametersResult_t *res);

    /// \brief Instructs firmware to wait for a specified time. - serializer
    /// \note For internal use only
    /// \param wait_time Wait time specified in UQ32.0 format having 5 ns resolution. Maximum value is 80 ms.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _waitSerialize(uint32_t wait_time, uint32_t *payload, uint8_t *payload_length);

    /// \brief Read or clear reset reason (previous error status). - serializer
    /// \note For internal use only
    /// \param action Action to be performed
    /// \param error_mask_1 Error word mask to specify which error of Error Status 1' shall be cleared.
    /// \param error_mask_1_present Flag to indicate whether the field error_mask_1 should be serialized
    /// \param length Number of words in error_mask_2
    /// \param error_mask_2 Error word mask to specify which error of Error Status 2' shall be cleared.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    /// \retval IFXRFE_E_MISSING_PARAMETER if array is NULL and length greater 0
    error_t _handleResetReasonSerialize(uint8_t action, uint16_t error_mask_1, bool error_mask_1_present, uint8_t length, const uint32_t *error_mask_2, uint32_t *payload, uint8_t *payload_length);

    /// \brief Read or clear reset reason (previous error status). - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _handleResetReasonParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_handleResetReasonResult_t *res);

    /// \brief Execute a series of command handles. - serializer
    /// \note For internal use only
    /// \param length Number of command handles to be executed in this batch.
    /// \param handle Command handle to be executed in this batch.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    /// \retval IFXRFE_E_MISSING_PARAMETER if array is NULL and length greater 0
    error_t _runBatchSerialize(uint8_t length, const uint8_t *handle, uint32_t *payload, uint8_t *payload_length);

    /// \brief Execute a series of command handles. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _runBatchParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_runBatchResult_t *res);

    /// \brief Abort the Sequencer. - serializer
    /// \note For internal use only
    /// \param disable_all_tx_pa Disable all TX1-4 power amplifiers?
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _abortRampScenarioSerialize(uint8_t disable_all_tx_pa, uint32_t *payload, uint8_t *payload_length);

    /// \brief Abort the Sequencer. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _abortRampScenarioParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_abortRampScenarioResult_t *res);

    /// \brief Configure Digital IO Settings - serializer
    /// \note For internal use only
    /// \param config_mask_ext If a pin is selected in the config mask, none of the three settings can be "not selected"
    /// \param clkmcu_drive_strength Select drive strength
    /// \param clkmcu_driver_config Select push-pull or open-drain configuration.
    /// \param clkmcu_pull_config Select tri-state, pull-down or pull-up configuration.
    /// \param dmux1_drive_strength Select drive strength
    /// \param dmux1_driver_config Select push-pull or open-drain configuration.
    /// \param dmux1_pull_config Select tri-state, pull-down or pull-up configuration.
    /// \param dmux2_drive_strength Select drive strength
    /// \param dmux2_driver_config Select push-pull or open-drain configuration.
    /// \param dmux2_pull_config Select tri-state, pull-down or pull-up configuration.
    /// \param dmux3_drive_strength Select drive strength
    /// \param dmux3_driver_config Select push-pull or open-drain configuration.
    /// \param dmux3_pull_config Select tri-state, pull-down or pull-up configuration.
    /// \param so_drive_strength Select drive strength
    /// \param so_driver_config Select push-pull or open-drain configuration.
    /// \param so_pull_config Select tri-state, pull-down or pull-up configuration.
    /// \param rft_drive_strength Select drive strength
    /// \param rft_driver_config Select push-pull or open-drain configuration.
    /// \param rft_pull_config Select tri-state, pull-down or pull-up configuration.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _configureDiosSerialize(uint16_t config_mask_ext, uint8_t clkmcu_drive_strength, uint8_t clkmcu_driver_config, uint8_t clkmcu_pull_config, uint8_t dmux1_drive_strength, uint8_t dmux1_driver_config, uint8_t dmux1_pull_config, uint8_t dmux2_drive_strength, uint8_t dmux2_driver_config, uint8_t dmux2_pull_config, uint8_t dmux3_drive_strength, uint8_t dmux3_driver_config, uint8_t dmux3_pull_config, uint8_t so_drive_strength, uint8_t so_driver_config, uint8_t so_pull_config, uint8_t rft_drive_strength, uint8_t rft_driver_config, uint8_t rft_pull_config, uint32_t *payload, uint8_t *payload_length);

    /// \brief Execute RX specific measurement routines. - serializer
    /// \note For internal use only
    /// \param measurement_sub_func_id Flags for the measurement routines to be performed:
    /// \param nmod TX modulator (DPLL) static frequency during measurement.
    /// \param hp_sel RX Chain HP corner frequency selection for BB measurements.
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _measureRxSerialize(uint16_t measurement_sub_func_id, uint32_t nmod, uint8_t hp_sel, uint32_t *payload, uint8_t *payload_length);

    /// \brief Execute RX specific measurement routines. - parse
    /// \note For internal use only
    /// \param payload Pointer to the payload of the raw response from the CTRX
    /// \param payload_length Number of payload words
    /// \param res [out] Parse result, pass NULL if not required
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_UNEXPECTED_VALUE if response length does not match
    /// \retval IFXRFE_E_FAILED if receid data length does not match the length field (for array return values with explicit length field only)
    error_t _measureRxParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_measureRxResult_t *res);

    /// \brief  - serializer
    /// \note For internal use only
    /// \param length
    /// \param offset
    /// \param region
    /// \param res_identifier
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _writeResultsSerialize(uint16_t length, uint16_t offset, uint8_t region, uint32_t res_identifier, uint32_t *payload, uint8_t *payload_length);

    /// \brief Finalize the firmware download and execute an application reset (no return if successful, since it will execute a reset). - serializer
    /// \note For internal use only
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _finishFwDownloadSerialize(uint32_t *payload, uint8_t *payload_length);

    /// \brief Set General Purpose Signals. - serializer
    /// \note For internal use only
    /// \param signal_bit_mask Mask of signal bits to set:
    /// \param signal_bit_value Value of signal bits:
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _setSignalsSerialize(uint8_t signal_bit_mask, uint8_t signal_bit_value, uint32_t *payload, uint8_t *payload_length);

    /// \brief Configure and trigger the LBIST  (no return if LBIST is triggered, since it will execute a reset). - serializer
    /// \note For internal use only
    /// \param payload [out] The buffer in which the parameters are serialized
    /// \param payload_length [out] The number of payload words written
    /// \retval IFXRFE_E_SUCCESS on success
    /// \retval IFXRFE_E_INVALID_SIZE if length is too high
    /// \retval IFXRFE_E_INVALID_PARAMETER if parameter out of range
    error_t _triggerLbistSerialize(uint32_t *payload, uint8_t *payload_length);


#ifdef __cplusplus
}  // namespace IfxRfe_Ctrx8188
#endif

#endif  //IFXRFE_FIRMWARECOMMANDS_SERDES_H_8188