/*
 * (c) (2022-2023), Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees.
 *
 * \warning   Autogenerated file. Do not edit!
 * generated on: 2026.03.04. 15:07
 * generated from interface specification revision: f00fa7c1
 * generated for CTRX firmware revision: 1.0.0-qsr.rc1
 * generated with metalib release 1.2.0.beta
 * generated with metagen version 0.8.0.0
 */

#include "IfxRfe_FirmwareCommands_Serdes.h"

#include "IfxRfe_Buffers.h"
#include "IfxRfe_Logger.h"
#include <stddef.h>
#include <string.h>

#ifdef __cplusplus
namespace IfxRfe_Ctrx8188
{
#endif

    /******************************************************************************/
    /*--------------------------------Defines-------------------------------------*/
    /******************************************************************************/

#define CHECK_PARAM_RANGE(param, min, max) \
    if ((param < min) || (param > max))    \
    {                                      \
        errorLog("invalid " #param);       \
        return IFXRFE_E_INVALID_PARAMETER; \
    }

#define CHECK_PARAM_ARRAY_RANGE(param, length, min, max) \
    for (int i = 0; i < length; i++)                     \
    {                                                    \
        if ((param[i] < min) || (param[i] > max))        \
        {                                                \
            errorLog("invalid " #param);                 \
            return IFXRFE_E_INVALID_PARAMETER;           \
        }                                                \
    }

#define CHECK_PARAM_GREATER(param, max)    \
    if (param > max)                       \
    {                                      \
        errorLog("invalid " #param);       \
        return IFXRFE_E_INVALID_PARAMETER; \
    }

#define CHECK_PARAM_ARRAY_GREATER(param, length, max) \
    for (int i = 0; i < length; i++)                  \
    {                                                 \
        if (param[i] > max)                           \
        {                                             \
            errorLog("invalid " #param);              \
            return IFXRFE_E_INVALID_PARAMETER;        \
        }                                             \
    }

#define CHECK_PARAM_LESS(param, min)       \
    if (param < min)                       \
    {                                      \
        errorLog("invalid " #param);       \
        return IFXRFE_E_INVALID_PARAMETER; \
    }

#define CHECK_PARAM_ARRAY_LESS(param, length, min) \
    for (int i = 0; i < length; i++)               \
    {                                              \
        if (param[i] < min)                        \
        {                                          \
            errorLog("invalid " #param);           \
            return IFXRFE_E_INVALID_PARAMETER;     \
        }                                          \
    }

#define CHECK_PARAM_GREATER_IF_PRESENT(param, max, present) \
    if ((param > max) && present)                           \
    {                                                       \
        errorLog("invalid " #param);                        \
        return IFXRFE_E_INVALID_PARAMETER;                  \
    }

#define MASK_SHIFT(value, bitmask, shiftleft) (((uint32_t)value & bitmask) << shiftleft)

    /******************************************************************************/
    /*-------------------------Serializers/deserializers--------------------------*/
    /******************************************************************************/
    error_t _writeMemorySerialize(uint8_t region, uint8_t length, uint32_t passkey, uint32_t start_addr, const uint32_t *data_word, uint32_t *payload, uint8_t *payload_length)
    {
        // Check array length
        if (length > MAX_REQ_PAYLOAD_WORDS - 3)  //3 scalar word(s) in the payload
        {
            return IFXRFE_E_INVALID_SIZE;
        }
        // Check array pointers
        if ((NULL == data_word) && (length != 0))
        {
            errorLog("Array is NULL but length is not 0");
            return IFXRFE_E_MISSING_PARAMETER;
        }
        // Transform request parameters
        payload[0] = length;
        payload[0] |= (region << 8);
        payload[1] = passkey;
        payload[2] = start_addr;
        memcpy(&payload[3], data_word, length * sizeof(uint32_t));

        *payload_length = 3 + length;

        return IFXRFE_E_SUCCESS;
    }

    error_t _readMemorySerialize(uint8_t region, uint8_t length, uint32_t passkey, uint32_t from_addr, uint32_t *payload, uint8_t *payload_length)
    {
        // Check array length
        if (length > MAX_RES_PAYLOAD_WORDS - 3)  //3 scalar word(s) in the payload
        {
            return IFXRFE_E_INVALID_SIZE;
        }
        // Transform request parameters
        payload[0] = length;
        payload[0] |= (region << 8);
        payload[1] = passkey;
        payload[2] = from_addr;

        *payload_length = 3;

        return IFXRFE_E_SUCCESS;
    }

    error_t _readMemoryParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_readMemoryResult_t *res)
    {
        if (payload_length < 2)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->region         = (payload[0] >> 8) & 0xFF;
        res->length         = payload[0] & 0xFF;
        res->from_addr      = payload[1];
        uint8_t arrayLength = payload_length - 2;
        if (res->length != arrayLength)  //make sure that the length field is correct
        {
            errorLogFmt("readMemory length field indicates %d but array length is %d", res->length, arrayLength);
            return IFXRFE_E_FAILED;
        }
        memcpy(res->data_word, &payload[2], arrayLength * sizeof(uint32_t));

        return IFXRFE_E_SUCCESS;
    }

    error_t _downloadFwFunctionsSerialize(uint8_t key1, uint8_t length, uint32_t key2, uint32_t key3, const uint32_t *code_word, uint32_t *payload, uint8_t *payload_length)
    {
        // Check array length
        if (length > MAX_REQ_PAYLOAD_WORDS - 3)  //3 scalar word(s) in the payload
        {
            return IFXRFE_E_INVALID_SIZE;
        }
        // Check array pointers
        if ((NULL == code_word) && (length != 0))
        {
            errorLog("Array is NULL but length is not 0");
            return IFXRFE_E_MISSING_PARAMETER;
        }
        // Transform request parameters
        payload[0] = length;
        payload[0] |= (key1 << 8);
        payload[1] = key2;
        payload[2] = key3;
        memcpy(&payload[3], code_word, length * sizeof(uint32_t));

        *payload_length = 3 + length;

        return IFXRFE_E_SUCCESS;
    }

    error_t _initializeSerialize(uint8_t length, const uint32_t *iram_descriptor, const uint32_t *value, uint32_t *payload, uint8_t *payload_length)
    {
        // Check array length
        if (length > (MAX_REQ_PAYLOAD_WORDS - 1) / 2)  //1 scalar word(s) in the payload, 2x vector parameters
        {
            return IFXRFE_E_INVALID_SIZE;
        }
        // Check array pointers
        if ((NULL == iram_descriptor || NULL == value) && (length != 0))
        {
            errorLog("Array is NULL but length is not 0");
            return IFXRFE_E_MISSING_PARAMETER;
        }
        // Transform request parameters
        payload[0] = length;
        for (uint8_t i = 0; i < length; i++)
        {
            payload[1 + (2 * i)] = iram_descriptor[i];
            payload[2 + (2 * i)] = value[i];
        }

        *payload_length = 1 + (length * 2);  //multiple vector parameters


        return IFXRFE_E_SUCCESS;
    }

    error_t _executeCalibrationSerialize(uint16_t calib_sub_func_id, uint32_t tx_ch_pow_idx, uint16_t ref_temp_idx, uint16_t limit_temp, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(calib_sub_func_id, 32767);
        CHECK_PARAM_GREATER(ref_temp_idx, 16);
        CHECK_PARAM_GREATER(limit_temp, 32767);

        // Transform request parameters
        payload[0] = (calib_sub_func_id & 0x7FFF);
        payload[1] = tx_ch_pow_idx;
        payload[2] = ref_temp_idx;
        payload[2] |= (limit_temp << 16);

        *payload_length = 3;

        return IFXRFE_E_SUCCESS;
    }

    error_t _executeCalibrationParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_executeCalibrationResult_t *res)
    {
        if (payload_length != 2)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->calib_sub_func_sum = payload[0] & 0x7FFF;
        res->skipped_calib_flag = (payload[0] >> 31) & 0x1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _configureDmuxSerialize(uint8_t config_mask, uint8_t dmux1_alt_signal, uint8_t dmux1_dir, uint8_t dmux1_pulse_duration_ext, uint8_t dmux2_alt_signal, uint8_t dmux2_dir, uint8_t dmux2_pulse_duration_ext, uint8_t dmux3_alt_signal, uint8_t dmux3_dir, uint8_t dmux3_pulse_duration_ext, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(config_mask, 7);
        CHECK_PARAM_GREATER(dmux1_dir, 1);
        CHECK_PARAM_GREATER(dmux1_pulse_duration_ext, 63);
        CHECK_PARAM_GREATER(dmux2_dir, 1);
        CHECK_PARAM_GREATER(dmux2_pulse_duration_ext, 63);
        CHECK_PARAM_GREATER(dmux3_dir, 1);
        CHECK_PARAM_GREATER(dmux3_pulse_duration_ext, 63);
        // Transform request parameters
        payload[0] = (config_mask & 0x7);
        payload[1] = dmux1_alt_signal;
        payload[1] |= ((dmux1_dir & 0x1) << 8);
        payload[1] |= ((dmux1_pulse_duration_ext & 0x3F) << 10);
        payload[1] |= (dmux2_alt_signal << 16);
        payload[1] |= ((dmux2_dir & 0x1) << 24);
        payload[1] |= ((dmux2_pulse_duration_ext & 0x3F) << 26);
        payload[2] = dmux3_alt_signal;
        payload[2] |= ((dmux3_dir & 0x1) << 8);
        payload[2] |= ((dmux3_pulse_duration_ext & 0x3F) << 10);

        *payload_length = 3;

        return IFXRFE_E_SUCCESS;
    }

    error_t _configureRampScenarioSerialize(uint16_t startoffset, uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = startoffset;

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _startRampScenarioSerialize(uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = 0;

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _finishRampScenarioSerialize(uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = 0;

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _finishRampScenarioParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_finishRampScenarioResult_t *res)
    {
        if (payload_length != 5)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->sequencer_run_res          = payload[0];
        res->sequencer_res_identifier   = payload[1];
        res->sequencer_dbg_res_id       = payload[2];
        res->thresh_sense_res_id        = payload[3];
        res->thresh_sense_segment_count = payload[4];

        return IFXRFE_E_SUCCESS;
    }

    error_t _getResultsSerialize(uint8_t interface, uint16_t length, uint16_t offset, uint32_t res_identifier, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(interface, 1);
        CHECK_PARAM_GREATER(length, 4095);
        CHECK_PARAM_GREATER(offset, 4095);
        // Check array length
        if (length > MAX_RES_PAYLOAD_WORDS - 2)  //2 scalar word(s) in the payload
        {
            return IFXRFE_E_INVALID_SIZE;
        }
        // Transform request parameters
        payload[0] = (length & 0xFFF);
        payload[0] |= ((interface & 0x3) << 14);
        payload[1] = (offset & 0xFFF);
        payload[2] = res_identifier;

        *payload_length = 3;

        return IFXRFE_E_SUCCESS;
    }

    error_t _getResultsParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_getResultsResult_t *res)
    {
        if (payload_length < 1)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->length         = payload[0] & 0xFFF;
        res->interface      = (payload[0] >> 12) & 0x3;
        uint8_t arrayLength = payload_length - 1;
        if (res->length != arrayLength)  //make sure that the length field is correct
        {
            errorLogFmt("getResults length field indicates %d but array length is %d", res->length, arrayLength);
            return IFXRFE_E_FAILED;
        }
        memcpy(res->data_word, &payload[1], arrayLength * sizeof(uint32_t));

        return IFXRFE_E_SUCCESS;
    }

    error_t _clearResultsSerialize(uint8_t clr_areas_msk, uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = clr_areas_msk;

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _gotoLowPowerSerialize(uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = 0;

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _getTemperatureSerialize(uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = 0;

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _getTemperatureParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_getTemperatureResult_t *res)
    {
        if (payload_length != 1)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->temp1 = (payload[0] >> 16) & 0xFFFF;
        res->temp2 = payload[0] & 0xFFFF;

        return IFXRFE_E_SUCCESS;
    }

    error_t _measureTxSerialize(uint8_t mode, uint8_t ch_mask, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(mode, 3);
        // Transform request parameters
        payload[0] = ch_mask;
        payload[0] |= ((mode & 0x3) << 8);

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _measureTxParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_measureTxResult_t *res)
    {
        if (payload_length != 5)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->ch_mask = payload[0] & 0xFF;
        res->mode    = (payload[0] >> 8) & 0x3;
        res->phase   = (payload[0] >> 16) & 0xFFFF;
        memcpy(res->pow_tx, &payload[1], 8 * sizeof(uint16_t));

        return IFXRFE_E_SUCCESS;
    }

    error_t _executeMonitoringSerialize(uint8_t detail_result, uint16_t monitoring_sub_func_id, uint32_t nmod, uint8_t tx_ch_mask, uint8_t hp_sel, const uint8_t pl_tx[8], const uint16_t phase_tx[8], uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(detail_result, 1);
        CHECK_PARAM_GREATER(monitoring_sub_func_id, 32767);
        CHECK_PARAM_GREATER(nmod, 67108863);
        CHECK_PARAM_GREATER(hp_sel, 4);
        CHECK_PARAM_ARRAY_GREATER(pl_tx, 8, 3);
        CHECK_PARAM_ARRAY_GREATER(phase_tx, 8, 511);

        // Check mandatory array pointers
        if ((NULL == pl_tx) || (NULL == phase_tx))
        {
            errorLog("Mandatory array is NULL");
            return IFXRFE_E_MISSING_PARAMETER;
        }
        // Transform request parameters
        payload[0] = (monitoring_sub_func_id & 0x7FFF);
        payload[0] |= ((detail_result & 0x1) << 15);
        payload[1] = (nmod & 0x3FFFFFF);
        payload[2] = tx_ch_mask;
        payload[2] |= ((hp_sel & 0x7) << 20);
        memset(&payload[3], 0, 16);
        uint8_t *ptr = (uint8_t *)&payload[1];
        for (int i = 0; i < 8; i++)
        {
            *(uint8_t *)(ptr + i * 2) |= (pl_tx[i] & 0x3);
            *(uint16_t *)(ptr + i * 2) |= ((phase_tx[i] & 0x1FF) << 7);
        }

        *payload_length = 7;

        return IFXRFE_E_SUCCESS;
    }

    error_t _executeMonitoringParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_executeMonitoringResult_t *res)
    {
        if (payload_length != 2)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->monitoring_sub_func_sum = payload[0] & 0x7FFF;
        res->res_identifier          = payload[1];

        return IFXRFE_E_SUCCESS;
    }

    error_t _calculateMemoryCrcSerialize(uint8_t region, uint32_t passkey, uint32_t from_addr, uint32_t length, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(length, 1048575);

        // Transform request parameters
        payload[0] = region;
        payload[1] = passkey;
        payload[2] = from_addr;
        payload[3] = length;

        *payload_length = 4;

        return IFXRFE_E_SUCCESS;
    }

    error_t _calculateMemoryCrcParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_calculateMemoryCrcResult_t *res)
    {
        if (payload_length != 1)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->crc = payload[0];

        return IFXRFE_E_SUCCESS;
    }

    error_t _configureRfFrequencySerialize(uint8_t bc, uint32_t nmod, uint32_t ncw, uint32_t rampbw, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(bc, 1);
        CHECK_PARAM_GREATER(nmod, 67108863);
        CHECK_PARAM_GREATER(ncw, 536870911);
        CHECK_PARAM_GREATER(rampbw, 33554431);
        // Transform request parameters
        payload[0] = (bc & 0x1);
        payload[1] = (nmod & 0x3FFFFFF);
        payload[2] = (ncw & 0x1FFFFFFF);
        payload[3] = (rampbw & 0x1FFFFFF);

        *payload_length = 4;

        return IFXRFE_E_SUCCESS;
    }

    error_t _configureMmicClockSerialize(uint8_t clock_selection, uint8_t clkout_source_resistance, uint8_t clkout_bias_voltage, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(clock_selection, 15);
        CHECK_PARAM_GREATER(clkout_source_resistance, 1);
        CHECK_PARAM_GREATER(clkout_bias_voltage, 1);

        // Transform request parameters
        payload[0] = (clock_selection & 0xF);
        payload[0] |= ((clkout_source_resistance & 0x1) << 4);
        payload[0] |= ((clkout_bias_voltage & 0x1) << 5);
        payload[0] |= (100 << 6);

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _configureTxPowerSerialize(uint8_t action_mask, uint8_t ch_mask, uint16_t tx_pa_slope_scale_fact, const uint16_t plvl[4], uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(action_mask, 3);
        CHECK_PARAM_RANGE(tx_pa_slope_scale_fact, 1, 1280);
        CHECK_PARAM_ARRAY_GREATER(plvl, 4, 2560);

        // Check mandatory array pointers
        if ((NULL == plvl))
        {
            errorLog("Mandatory array is NULL");
            return IFXRFE_E_MISSING_PARAMETER;
        }
        // Transform request parameters
        payload[0] = ch_mask;
        payload[0] |= ((action_mask & 0x3) << 8);
        payload[3] = tx_pa_slope_scale_fact;
        memcpy(&payload[1], &plvl[0], 4 * sizeof(plvl[0]));


        *payload_length = 4;

        return IFXRFE_E_SUCCESS;
    }

    error_t _setTxOutputSerialize(uint8_t ch_mask, uint8_t action_mask, const uint8_t pl_tx[8], const uint16_t phase_tx[8], uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(action_mask, 7);
        CHECK_PARAM_ARRAY_GREATER(pl_tx, 8, 3);
        CHECK_PARAM_ARRAY_GREATER(phase_tx, 8, 511);

        // Check mandatory array pointers
        if ((NULL == pl_tx) || (NULL == phase_tx))
        {
            errorLog("Mandatory array is NULL");
            return IFXRFE_E_MISSING_PARAMETER;
        }
        // Transform request parameters
        payload[0] = ch_mask;
        payload[0] |= ((action_mask & 0x7) << 8);
        memset(&payload[1], 0, 16);
        uint8_t *ptr = (uint8_t *)&payload[1];
        for (int i = 0; i < 8; i++)
        {
            *(uint8_t *)(ptr + i * 2) |= (pl_tx[i] & 0x3);
            *(uint16_t *)(ptr + i * 2) |= ((phase_tx[i] & 0x1FF) << 7);
        }

        *payload_length = 5;

        return IFXRFE_E_SUCCESS;
    }

    error_t _configureRxSerialize(uint8_t data_width_sel, uint8_t gain_sel, uint8_t data_rate_sel, uint8_t start_mode, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(data_width_sel, 4);
        CHECK_PARAM_GREATER(gain_sel, 15);
        CHECK_PARAM_GREATER(data_rate_sel, 31);
        CHECK_PARAM_GREATER(start_mode, 1);

        // Transform request parameters
        payload[0] = ((data_width_sel & 0x7) << 4);
        payload[0] |= ((gain_sel & 0xF) << 8);
        payload[1] = ((data_rate_sel & 0x1F) << 16);
        payload[1] |= ((start_mode & 0x3) << 28);

        *payload_length = 2;

        return IFXRFE_E_SUCCESS;
    }

    error_t _setMmicClockSerialize(uint8_t action_mask, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(action_mask, 3);
        // Transform request parameters
        payload[0] = (action_mask & 0x3);

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _getVersionSerialize(uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = 0;

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _getVersionParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_getVersionResult_t *res)
    {
        if (payload_length != 4)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->fw_version_code = payload[0];
        res->silicon_version = payload[1] & 0x1FFF;
        res->chip_id_lo      = payload[2];
        res->chip_id_hi      = payload[3];

        return IFXRFE_E_SUCCESS;
    }

    error_t _gotoOperationSerialize(uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = 255;
        payload[0] |= (1 << 8);
        payload[0] |= (1 << 9);
        payload[0] |= (0 << 13);

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _setClockOutputSerialize(uint8_t clkmcu_action, uint8_t clkmcu_freq, uint8_t clkphy_action, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(clkmcu_action, 2);
        CHECK_PARAM_GREATER(clkmcu_freq, 2);
        CHECK_PARAM_GREATER(clkphy_action, 2);

        // Transform request parameters
        payload[0] = (clkmcu_action & 0x3);
        payload[0] |= ((clkmcu_freq & 0x3) << 4);
        payload[0] |= ((clkphy_action & 0x3) << 8);

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _getStatusSerialize(uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = 0;

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _getStatusParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_getStatusResult_t *res)
    {
        if (payload_length != 1)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->curr_state = payload[0];

        return IFXRFE_E_SUCCESS;
    }

    error_t _exitPreOperationSerialize(uint32_t rom_fw_ver, uint32_t ram_fw_ver, uint32_t auth_data, uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = 0;
        payload[1] = rom_fw_ver;
        payload[2] = ram_fw_ver;
        payload[3] = auth_data;

        *payload_length = 4;

        return IFXRFE_E_SUCCESS;
    }

    error_t _handleErrorSerialize(uint8_t action, uint16_t error_mask_1, bool error_mask_1_present, uint8_t length, const uint32_t *error_mask_2, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(action, 3);
        CHECK_PARAM_GREATER_IF_PRESENT(error_mask_1, 511, error_mask_1_present);
        CHECK_PARAM_GREATER(length, 8);

        // Check array pointers
        if ((NULL == error_mask_2) && (length != 0))
        {
            errorLog("Array is NULL but length is not 0");
            return IFXRFE_E_MISSING_PARAMETER;
        }
        // Transform request parameters
        *payload_length = 0;

        payload[*payload_length] = (action & 0x3);
        (*payload_length)++;

        payload[*payload_length] = (error_mask_1_present) ? (error_mask_1 & 0x1FF) : 0;
        *payload_length += (error_mask_1_present) ? 1 : 0;

        memcpy(&payload[*payload_length], error_mask_2, length * sizeof(uint32_t));
        *payload_length += length;

        return IFXRFE_E_SUCCESS;
    }

    error_t _handleErrorParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_handleErrorResult_t *res)
    {
        if (payload_length < 1)  //only check the length of the mandatory fields
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->failure_ind_m             = (payload[0] >> 1) & 0x1;
        res->failure_ind_a             = (payload[0] >> 2) & 0x1;
        res->failure_ind_b             = (payload[0] >> 3) & 0x1;
        res->failure_ind_c             = (payload[0] >> 4) & 0x1;
        res->optional_fields_available = false;
        if (payload_length > 1)  //if there are optional fields available, parse them
        {
            res->optional_fields_available = true;
            res->error_status_1            = payload[1] & 0x1FF;
            uint8_t arrayLength            = payload_length - 2;
            res->length                    = arrayLength;
            memcpy(res->error_status_2, &payload[2], arrayLength * sizeof(uint32_t));
        }

        return IFXRFE_E_SUCCESS;
    }

    error_t _getRxTfParametersSerialize(uint8_t hp, uint8_t gain_sel, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(hp, 4);
        CHECK_PARAM_GREATER(gain_sel, 15);
        // Transform request parameters
        payload[0] = (hp & 0x7);
        payload[0] |= ((gain_sel & 0xF) << 4);

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _getRxTfParametersParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_getRxTfParametersResult_t *res)
    {
        if (payload_length != 9)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->rx_temp_t1             = payload[0] & 0xFFFF;
        res->rx_temp_t2             = (payload[0] >> 16) & 0xFFFF;
        res->RX1_HP_MODEL_COEFF_T1  = payload[1] & 0xFF;
        res->RX2_HP_MODEL_COEFF_T1  = (payload[1] >> 8) & 0xFF;
        res->RX1_HP_MODEL_COEFF_T2  = (payload[1] >> 16) & 0xFF;
        res->RX2_HP_MODEL_COEFF_T2  = (payload[1] >> 24) & 0xFF;
        res->RX3_HP_MODEL_COEFF_T1  = payload[2] & 0xFF;
        res->RX4_HP_MODEL_COEFF_T1  = (payload[2] >> 8) & 0xFF;
        res->RX3_HP_MODEL_COEFF_T2  = (payload[2] >> 16) & 0xFF;
        res->RX4_HP_MODEL_COEFF_T2  = (payload[2] >> 24) & 0xFF;
        res->RX5_HP_MODEL_COEFF_T1  = payload[3] & 0xFF;
        res->RX6_HP_MODEL_COEFF_T1  = (payload[3] >> 8) & 0xFF;
        res->RX5_HP_MODEL_COEFF_T2  = (payload[3] >> 16) & 0xFF;
        res->RX6_HP_MODEL_COEFF_T2  = (payload[3] >> 24) & 0xFF;
        res->RX7_HP_MODEL_COEFF_T1  = payload[4] & 0xFF;
        res->RX8_HP_MODEL_COEFF_T1  = (payload[4] >> 8) & 0xFF;
        res->RX7_HP_MODEL_COEFF_T2  = (payload[4] >> 16) & 0xFF;
        res->RX8_HP_MODEL_COEFF_T2  = (payload[4] >> 24) & 0xFF;
        res->RX1_BBF_MODEL_COEFF_T1 = payload[5] & 0xFF;
        res->RX2_BBF_MODEL_COEFF_T1 = (payload[5] >> 8) & 0xFF;
        res->RX1_BBF_MODEL_COEFF_T2 = (payload[5] >> 16) & 0xFF;
        res->RX2_BBF_MODEL_COEFF_T2 = (payload[5] >> 24) & 0xFF;
        res->RX3_BBF_MODEL_COEFF_T1 = payload[6] & 0xFF;
        res->RX4_BBF_MODEL_COEFF_T1 = (payload[6] >> 8) & 0xFF;
        res->RX3_BBF_MODEL_COEFF_T2 = (payload[6] >> 16) & 0xFF;
        res->RX4_BBF_MODEL_COEFF_T2 = (payload[6] >> 24) & 0xFF;
        res->RX5_BBF_MODEL_COEFF_T1 = payload[7] & 0xFF;
        res->RX6_BBF_MODEL_COEFF_T1 = (payload[7] >> 8) & 0xFF;
        res->RX5_BBF_MODEL_COEFF_T2 = (payload[7] >> 16) & 0xFF;
        res->RX6_BBF_MODEL_COEFF_T2 = (payload[7] >> 24) & 0xFF;
        res->RX7_BBF_MODEL_COEFF_T1 = payload[8] & 0xFF;
        res->RX8_BBF_MODEL_COEFF_T1 = (payload[8] >> 8) & 0xFF;
        res->RX7_BBF_MODEL_COEFF_T2 = (payload[8] >> 16) & 0xFF;
        res->RX8_BBF_MODEL_COEFF_T2 = (payload[8] >> 24) & 0xFF;

        return IFXRFE_E_SUCCESS;
    }

    error_t _waitSerialize(uint32_t wait_time, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(wait_time, 16000000);

        // Transform request parameters
        payload[0] = (0 << 1);
        payload[1] = wait_time;

        *payload_length = 2;

        return IFXRFE_E_SUCCESS;
    }

    error_t _handleResetReasonSerialize(uint8_t action, uint16_t error_mask_1, bool error_mask_1_present, uint8_t length, const uint32_t *error_mask_2, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(action, 3);
        CHECK_PARAM_GREATER_IF_PRESENT(error_mask_1, 511, error_mask_1_present);
        CHECK_PARAM_GREATER(length, 8);

        // Check array pointers
        if ((NULL == error_mask_2) && (length != 0))
        {
            errorLog("Array is NULL but length is not 0");
            return IFXRFE_E_MISSING_PARAMETER;
        }
        // Transform request parameters
        *payload_length = 0;

        payload[*payload_length] = (action & 0x3);
        (*payload_length)++;

        payload[*payload_length] = (error_mask_1_present) ? (error_mask_1 & 0x1FF) : 0;
        *payload_length += (error_mask_1_present) ? 1 : 0;

        memcpy(&payload[*payload_length], error_mask_2, length * sizeof(uint32_t));
        *payload_length += length;

        return IFXRFE_E_SUCCESS;
    }

    error_t _handleResetReasonParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_handleResetReasonResult_t *res)
    {
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->optional_fields_available = false;
        if (payload_length > 0)  //if there are optional fields available, parse them
        {
            res->optional_fields_available = true;
            res->error_status_1            = payload[1] & 0x1FF;
            uint8_t arrayLength            = payload_length - 2;
            res->length                    = arrayLength;
            memcpy(res->error_status_2, &payload[2], arrayLength * sizeof(uint32_t));
        }

        return IFXRFE_E_SUCCESS;
    }

    error_t _runBatchSerialize(uint8_t length, const uint8_t *handle, uint32_t *payload, uint8_t *payload_length)
    {
        // Check array length
        if (length > (MAX_REQ_PAYLOAD_WORDS - 1) * 4)  //1 scalar word(s) in the payload, 4 vector parameters per word
        {
            return IFXRFE_E_INVALID_SIZE;
        }
        // Check array pointers
        if ((NULL == handle) && (length != 0))
        {
            errorLog("Array is NULL but length is not 0");
            return IFXRFE_E_MISSING_PARAMETER;
        }
        // Transform request parameters
        payload[0] = length;
        memcpy(&payload[1], handle, length * sizeof(uint8_t));

        *payload_length = 1 + 1 + ((length - 1) / (sizeof(uint32_t) / sizeof(uint8_t)));  //round up size to whole word


        return IFXRFE_E_SUCCESS;
    }

    error_t _runBatchParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_runBatchResult_t *res)
    {
        if (payload_length != 2)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->res_identifier   = payload[0];
        res->num_succ_handles = payload[1] & 0xFF;

        return IFXRFE_E_SUCCESS;
    }

    error_t _abortRampScenarioSerialize(uint8_t disable_all_tx_pa, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(disable_all_tx_pa, 1);
        // Transform request parameters
        payload[0] = (disable_all_tx_pa & 0x1);

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _abortRampScenarioParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_abortRampScenarioResult_t *res)
    {
        if (payload_length != 2)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->sequencer_run_res    = payload[0];
        res->sequencer_dbg_res_id = payload[1];

        return IFXRFE_E_SUCCESS;
    }

    error_t _configureDiosSerialize(uint16_t config_mask_ext, uint8_t clkmcu_drive_strength, uint8_t clkmcu_driver_config, uint8_t clkmcu_pull_config, uint8_t dmux1_drive_strength, uint8_t dmux1_driver_config, uint8_t dmux1_pull_config, uint8_t dmux2_drive_strength, uint8_t dmux2_driver_config, uint8_t dmux2_pull_config, uint8_t dmux3_drive_strength, uint8_t dmux3_driver_config, uint8_t dmux3_pull_config, uint8_t so_drive_strength, uint8_t so_driver_config, uint8_t so_pull_config, uint8_t rft_drive_strength, uint8_t rft_driver_config, uint8_t rft_pull_config, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(config_mask_ext, 2047);
        CHECK_PARAM_GREATER(clkmcu_drive_strength, 4);
        CHECK_PARAM_GREATER(clkmcu_driver_config, 2);
        CHECK_PARAM_GREATER(clkmcu_pull_config, 3);
        CHECK_PARAM_GREATER(dmux1_drive_strength, 4);
        CHECK_PARAM_GREATER(dmux1_driver_config, 2);
        CHECK_PARAM_GREATER(dmux1_pull_config, 3);
        CHECK_PARAM_GREATER(dmux2_drive_strength, 4);
        CHECK_PARAM_GREATER(dmux2_driver_config, 2);
        CHECK_PARAM_GREATER(dmux2_pull_config, 3);
        CHECK_PARAM_GREATER(dmux3_drive_strength, 4);
        CHECK_PARAM_GREATER(dmux3_driver_config, 2);
        CHECK_PARAM_GREATER(dmux3_pull_config, 3);
        CHECK_PARAM_GREATER(so_drive_strength, 4);
        CHECK_PARAM_GREATER(so_driver_config, 2);
        CHECK_PARAM_GREATER(so_pull_config, 3);
        CHECK_PARAM_GREATER(rft_drive_strength, 4);
        CHECK_PARAM_GREATER(rft_driver_config, 2);
        CHECK_PARAM_GREATER(rft_pull_config, 3);

        // Transform request parameters
        payload[0] = (config_mask_ext & 0x7FF);
        payload[1] = (clkmcu_drive_strength & 0x7);
        payload[1] |= ((clkmcu_driver_config & 0x3) << 3);
        payload[1] |= ((clkmcu_pull_config & 0x7) << 5);
        payload[1] |= ((dmux1_drive_strength & 0x7) << 8);
        payload[1] |= ((dmux1_driver_config & 0x3) << 11);
        payload[1] |= ((dmux1_pull_config & 0x7) << 13);
        payload[1] |= ((dmux2_drive_strength & 0x7) << 16);
        payload[1] |= ((dmux2_driver_config & 0x3) << 19);
        payload[1] |= ((dmux2_pull_config & 0x7) << 21);
        payload[1] |= ((dmux3_drive_strength & 0x7) << 24);
        payload[1] |= ((dmux3_driver_config & 0x3) << 27);
        payload[1] |= ((dmux3_pull_config & 0x7) << 29);
        payload[2] = (so_drive_strength & 0x7);
        payload[2] |= ((so_driver_config & 0x3) << 3);
        payload[2] |= ((so_pull_config & 0x7) << 5);
        payload[2] |= ((rft_drive_strength & 0x7) << 8);
        payload[2] |= ((rft_driver_config & 0x3) << 11);
        payload[2] |= ((rft_pull_config & 0x7) << 13);
        payload[3] = 0;

        *payload_length = 4;

        return IFXRFE_E_SUCCESS;
    }

    error_t _measureRxSerialize(uint16_t measurement_sub_func_id, uint32_t nmod, uint8_t hp_sel, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(measurement_sub_func_id, 32767);
        CHECK_PARAM_GREATER(nmod, 67108863);
        CHECK_PARAM_GREATER(hp_sel, 4);

        // Transform request parameters
        payload[0] = (measurement_sub_func_id & 0x7FFF);
        payload[1] = (nmod & 0x3FFFFFF);
        payload[2] = ((hp_sel & 0x7) << 20);

        *payload_length = 3;

        return IFXRFE_E_SUCCESS;
    }

    error_t _measureRxParse(const uint32_t *payload, uint8_t payload_length, IfxRfe_measureRxResult_t *res)
    {
        if (payload_length != 2)
        {
            return IFXRFE_E_UNEXPECTED_VALUE;
        }
        if (NULL == res)
        {
            return IFXRFE_E_SUCCESS;  //nothing to parse
        }
        res->measurement_sub_func_sum = payload[0] & 0x7FFF;
        res->res_identifier           = payload[1];

        return IFXRFE_E_SUCCESS;
    }

    error_t _writeResultsSerialize(uint16_t length, uint16_t offset, uint8_t region, uint32_t res_identifier, uint32_t *payload, uint8_t *payload_length)
    {
        // Check request parameters
        CHECK_PARAM_GREATER(length, 4095);
        CHECK_PARAM_GREATER(offset, 4095);
        // Transform request parameters
        payload[0] = (length & 0xFFF);
        payload[1] = (offset & 0xFFF);
        payload[1] |= (region << 16);
        payload[2] = res_identifier;

        *payload_length = 3;

        return IFXRFE_E_SUCCESS;
    }

    error_t _finishFwDownloadSerialize(uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = 0;

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _setSignalsSerialize(uint8_t signal_bit_mask, uint8_t signal_bit_value, uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = signal_bit_mask;
        payload[0] |= (signal_bit_value << 8);

        *payload_length = 1;

        return IFXRFE_E_SUCCESS;
    }

    error_t _triggerLbistSerialize(uint32_t *payload, uint8_t *payload_length)
    {
        // Transform request parameters
        payload[0] = 64;
        payload[1] = 100;
        payload[2] = 268435504;

        *payload_length = 3;

        return IFXRFE_E_SUCCESS;
    }


#ifdef __cplusplus
}  // namespace IfxRfe_Ctrx8188
#endif
