/*
 * (c) (2022-2023), Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees.
 *
 * \warning   Autogenerated file. Do not edit!
 * generated on: 2026.03.04. 15:07
 * generated from interface specification revision: f00fa7c1
 * generated for CTRX firmware revision: 1.0.0-qsr.rc1
 * generated with metalib release 1.2.0.beta
 * generated with metagen version 0.8.0.0
 */


#ifndef IFXRFE_CTRXOPCODES_H_8188
#define IFXRFE_CTRXOPCODES_H_8188 1

#ifdef __cplusplus
namespace IfxRfe_Ctrx8188
{
#endif

// Firmware command codes
#define IFXRFE_FW_COMMAND_WRITE_MEMORY            0x10
#define IFXRFE_FW_COMMAND_READ_MEMORY             0x12
#define IFXRFE_FW_COMMAND_DOWNLOAD_FW_FUNCTIONS   0x14
#define IFXRFE_FW_COMMAND_INITIALIZE              0x15
#define IFXRFE_FW_COMMAND_EXECUTE_CALIBRATION     0x16
#define IFXRFE_FW_COMMAND_CONFIGURE_DMUX          0x17
#define IFXRFE_FW_COMMAND_CONFIGURE_RAMP_SCENARIO 0x18
#define IFXRFE_FW_COMMAND_START_RAMP_SCENARIO     0x19
#define IFXRFE_FW_COMMAND_FINISH_RAMP_SCENARIO    0x1A
#define IFXRFE_FW_COMMAND_GET_RESULTS             0x1B
#define IFXRFE_FW_COMMAND_CLEAR_RESULTS           0x1C
#define IFXRFE_FW_COMMAND_GOTO_LOW_POWER          0x1D
#define IFXRFE_FW_COMMAND_GET_TEMPERATURE         0x1E
#define IFXRFE_FW_COMMAND_MEASURE_TX              0x1F
#define IFXRFE_FW_COMMAND_EXECUTE_MONITORING      0x20
#define IFXRFE_FW_COMMAND_CALCULATE_MEMORY_CRC    0x21
#define IFXRFE_FW_COMMAND_CONFIGURE_RF_FREQUENCY  0x22
#define IFXRFE_FW_COMMAND_CONFIGURE_MMIC_CLOCK    0x24
#define IFXRFE_FW_COMMAND_CONFIGURE_TX_POWER      0x25
#define IFXRFE_FW_COMMAND_SET_TX_OUTPUT           0x26
#define IFXRFE_FW_COMMAND_CONFIGURE_RX            0x27
#define IFXRFE_FW_COMMAND_SET_MMIC_CLOCK          0x29
#define IFXRFE_FW_COMMAND_GET_VERSION             0x2A
#define IFXRFE_FW_COMMAND_GOTO_OPERATION          0x2B
#define IFXRFE_FW_COMMAND_SET_CLOCK_OUTPUT        0x2C
#define IFXRFE_FW_COMMAND_GET_STATUS              0x2D
#define IFXRFE_FW_COMMAND_EXIT_PRE_OPERATION      0x2E
#define IFXRFE_FW_COMMAND_HANDLE_ERROR            0x2F
#define IFXRFE_FW_COMMAND_GET_RX_TF_PARAMETERS    0x30
#define IFXRFE_FW_COMMAND_WAIT                    0x31
#define IFXRFE_FW_COMMAND_HANDLE_RESET_REASON     0x32
#define IFXRFE_FW_COMMAND_RUN_BATCH               0x33
#define IFXRFE_FW_COMMAND_ABORT_RAMP_SCENARIO     0x34
#define IFXRFE_FW_COMMAND_CONFIGURE_DIOS          0x36
#define IFXRFE_FW_COMMAND_MEASURE_RX              0x37
#define IFXRFE_FW_COMMAND_WRITE_RESULTS           0x38
#define IFXRFE_FW_COMMAND_FINISH_FW_DOWNLOAD      0x39
#define IFXRFE_FW_COMMAND_SET_SIGNALS             0x3A
#define IFXRFE_FW_COMMAND_TRIGGER_LBIST           0x3B

#ifdef __cplusplus
}  // namespace IfxRfe_Ctrx8188
#endif

#endif  //IFXRFE_CTRXOPCODES_H_8188