/*
 * (c) (2022-2023), Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees.
 *
 * \warning   Autogenerated file. Do not edit!
 * generated on: 2026.03.04. 15:07
 * generated from interface specification revision: f00fa7c1
 * generated for CTRX firmware revision: 1.0.0-qsr.rc1
 * generated with metalib release 1.2.0.beta
 * generated with metagen version 0.8.0.0
 */

#ifndef IFXRFE_CTRXCOMMANDPARAMS_H_8188
#define IFXRFE_CTRXCOMMANDPARAMS_H_8188 1

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
namespace IfxRfe_Ctrx8188
{
#endif

    typedef struct
    {
        uint8_t region;       ///> Region of memory to be written.
        uint8_t length;       ///> Number of data words to be written
        uint32_t passkey;     ///> Passkey to access given addresses
        uint32_t start_addr;  ///> Relative start address in the region to write Data Words
        uint32_t *data_word;  ///> Data words to be written
    } IfxRfe_writeMemory_t;

    typedef struct
    {
        uint8_t region;      ///> Region of memory to read from
        uint8_t length;      ///> Number of data words to be read
        uint32_t passkey;    ///> Passkey to access given addresses
        uint32_t from_addr;  ///> Relative start address in the region to read the data words
    } IfxRfe_readMemory_t;

    typedef struct
    {
        uint8_t region;          ///> Region of memory to read from
        uint8_t length;          ///> Number of data words to be read
        uint32_t from_addr;      ///> Relative start address in the region of data words read
        uint32_t data_word[30];  ///> Read data words
    } IfxRfe_readMemoryResult_t;

    typedef struct
    {
        uint8_t key1;         ///> Key1 value of the block to be downloaded.
        uint8_t length;       ///> Number of code words in the block.
        uint32_t key2;        ///> Key2 value of the block to be downloaded.
        uint32_t key3;        ///> Key3 value of the block to be downloaded.
        uint32_t *code_word;  ///> Code words of the block
    } IfxRfe_downloadFwFunctions_t;

    typedef struct
    {
        uint8_t length;             ///> Number of settings to be changed
        uint32_t *iram_descriptor;  ///> Specifies which setting to be changed
        uint32_t *value;            ///> New value of the setting
    } IfxRfe_initialize_t;

    typedef struct
    {
        uint16_t calib_sub_func_id;  ///> Flags for the calibrations to be performed:
        uint32_t tx_ch_pow_idx;      ///> If bit is set, perform the power calibration for the selected power index of the selected TX channel.
        uint16_t ref_temp_idx;       ///> Reference temperature index to decide if calibration should be executed (0 = no reference temperature).
        uint16_t limit_temp;         ///> Temperature difference limit to avoid recalibration if actual temperature difference is less than this limit (in Q12.3 format).
    } IfxRfe_executeCalibration_t;

    typedef struct
    {
        uint16_t calib_sub_func_sum;  ///> Status summary bits for the calibration functions pass/fail (see request for bit assignments).
        uint8_t skipped_calib_flag;   ///> Flag if the calibration was skipped because the current temperature was within the limit.
    } IfxRfe_executeCalibrationResult_t;

    typedef struct
    {
        uint8_t config_mask;               ///> b0 = 1 Valid DMUX1 configuration
        uint8_t dmux1_alt_signal;          ///> Digital signal routed through the DMUX pin (for input, set to 0h).
        uint8_t dmux1_dir;                 ///> DMUX pin direction input/output
        uint8_t dmux1_pulse_duration_ext;  ///> Optional output pulse duration extension (for input, set to 0h).
        uint8_t dmux2_alt_signal;          ///> see DMUX1 description
        uint8_t dmux2_dir;                 ///> see DMUX1 description
        uint8_t dmux2_pulse_duration_ext;  ///> see DMUX1 description
        uint8_t dmux3_alt_signal;          ///> see DMUX1 description
        uint8_t dmux3_dir;                 ///> see DMUX1 description
        uint8_t dmux3_pulse_duration_ext;  ///> see DMUX1 description
    } IfxRfe_configureDmux_t;

    typedef struct
    {
        uint16_t startoffset;  ///> Relative address in the sequencer memory from where to read the sequencer configuration.
    } IfxRfe_configureRampScenario_t;

    typedef struct
    {
        uint32_t sequencer_run_res;           ///> Sequencer run result (aborted because of errors (based on Sequencer's error registers) or successfully done)
        uint32_t sequencer_res_identifier;    ///> Sequencer result identifier
        uint32_t sequencer_dbg_res_id;        ///> Result identifier to detailed error information based on Sequencer's error registers.
        uint32_t thresh_sense_res_id;         ///> Result identifier to chirp-based RX saturation detection results
        uint32_t thresh_sense_segment_count;  ///> Total number of chirps with triggered RX saturation sensing during the ramp scenario
    } IfxRfe_finishRampScenarioResult_t;

    typedef struct
    {
        uint8_t interface;        ///> Interface for returning the results
        uint16_t length;          ///> Number of data words to read.
        uint16_t offset;          ///> Word offset within result to read from.
        uint32_t res_identifier;  ///> Identifies a result.
    } IfxRfe_getResults_t;

    typedef struct
    {
        uint16_t length;         ///> Number of data words read
        uint8_t interface;       ///> Interface for returning the results
        uint32_t data_word[31];  ///> Read data words returned if the selected interface is SPI.
    } IfxRfe_getResultsResult_t;

    typedef struct
    {
        uint8_t clr_areas_msk;  ///> Bitmask indicating which areas are to be cleared.
    } IfxRfe_clearResults_t;

    typedef struct
    {
        uint16_t temp1;  ///> Temperature value of the first DTS instance in degree Celsius in Q12.3 fixed-point format
        uint16_t temp2;  ///> Temperature value of the second DTS instance in degree Celsius in Q12.3 fixed-point format
    } IfxRfe_getTemperatureResult_t;

    typedef struct
    {
        uint8_t mode;     ///> Mode of measurement
        uint8_t ch_mask;  ///> Transmitter channel to be measured:
    } IfxRfe_measureTx_t;

    typedef struct
    {
        uint8_t ch_mask;     ///> Measured TX Channel (B0 = TX1..B7= TX8)
        uint8_t mode;        ///>
        uint16_t phase;      ///> Phase of the selected channel. Ignored if Mode is not Power and Phase
        uint16_t pow_tx[8];  ///> Power of TX Channel
    } IfxRfe_measureTxResult_t;

    typedef struct
    {
        uint8_t detail_result;            ///> Flag for enabling the writing of the monitoring result in the respective result area.
        uint16_t monitoring_sub_func_id;  ///> Flags for the monitoring functions to be performed.
        uint32_t nmod;                    ///> TX modulator (DPLL) static frequency during monitoring.
        uint8_t tx_ch_mask;               ///> Flags to specify on which TX channels to run the monitoring on.
        uint8_t hp_sel;                   ///> RX Chain HP corner frequency selection for BB Monitoring.
        uint8_t pl_tx[8];                 ///> Power level Index of the specified channel. Ignored if corresponding channel bit is not set in Channel Mask.
        uint16_t phase_tx[8];             ///> Phase index of the specified channel. Ignored if corresponding channel bit is not set in Channel Mask.
    } IfxRfe_executeMonitoring_t;

    typedef struct
    {
        uint16_t monitoring_sub_func_sum;  ///> Status summary bits for the monitoring functions pass/fail (see request for bit assignments).
        uint32_t res_identifier;           ///> Result Identifier to read monitoring data later by Get_Results() command.
    } IfxRfe_executeMonitoringResult_t;

    typedef struct
    {
        uint8_t region;      ///> Region of memory to calculate CRC from.
        uint32_t passkey;    ///> Passkey to access given addresses
        uint32_t from_addr;  ///> Relative start address in the region to calculate CRC (word aligned).
        uint32_t length;     ///> Number of data words to calculate CRC.
    } IfxRfe_calculateMemoryCrc_t;

    typedef struct
    {
        uint32_t crc;  ///> The CRC algorithm is specified in the Default Settings Table and, initially, is set to the same algorithm used for the SPI message CRC.
    } IfxRfe_calculateMemoryCrcResult_t;

    typedef struct
    {
        uint8_t bc;       ///> Switch to select whether band should be changed
        uint32_t nmod;    ///> NMOD (in Q5.20 format) is a parameter for TX modulator (DPLL) static frequency configuration.
        uint32_t ncw;     ///> NCW (in UQ9.20 format) is the new value for the upper band limit
        uint32_t rampbw;  ///> RAMPBW (in UQ5.20 format) is the new value for the bandwidth
    } IfxRfe_configureRfFrequency_t;

    typedef struct
    {
        uint8_t clock_selection;           ///> Clock configuration flags (0b to disable, 1b to enable).
        uint8_t clkout_source_resistance;  ///> CLKOUT source resistance selection.
        uint8_t clkout_bias_voltage;       ///> CLKOUT load bias voltage selection.
    } IfxRfe_configureMmicClock_t;

    typedef struct
    {
        uint8_t action_mask;              ///> Configuration action for the selected channels:
        uint8_t ch_mask;                  ///> Flags to specify which channels to configure.
        uint16_t tx_pa_slope_scale_fact;  ///> PA Slope scaling factor of TX, 2^-8..5.0 in UQ8.8 format for TX.
        uint16_t plvl[4];                 ///> Power back-off level of TX, 0..20[dB] in Q8.7 format.
    } IfxRfe_configureTxPower_t;

    typedef struct
    {
        uint8_t ch_mask;       ///> Flags to specify on which channels to perform the action.
        uint8_t action_mask;   ///> Action to be performed for the selected channels.
        uint8_t pl_tx[8];      ///> Power level Index of the specified channel. Ignored if corresponding channel bit is not set in Channel Mask.
        uint16_t phase_tx[8];  ///> Phase index of the specified channel. Ignored if corresponding channel bit is not set in Channel Mask.
    } IfxRfe_setTxOutput_t;

    typedef struct
    {
        uint8_t data_width_sel;  ///> RX Chain Data width selection
        uint8_t gain_sel;        ///> RX Chain gain selection.Used to apply a calibrated gain configuration at TIA, LPF, DFE and PF
        uint8_t data_rate_sel;   ///> HSRIF data rate selection for CSI2 operation
        uint8_t start_mode;      ///> HSRIF start mode for CSI2 operation
    } IfxRfe_configureRx_t;

    typedef struct
    {
        uint8_t action_mask;  ///> Actions which should be performed.
    } IfxRfe_setMmicClock_t;

    typedef struct
    {
        uint32_t fw_version_code;  ///> Version of the firmware
        uint16_t silicon_version;  ///> Infineon silicon version including design step, mask & metal version.
        uint32_t chip_id_lo;       ///> Low word of e-fuse chip-ID.
        uint32_t chip_id_hi;       ///> High word of e-fuse chip-ID.
    } IfxRfe_getVersionResult_t;

    typedef struct
    {
        uint8_t clkmcu_action;  ///> Enable/Disable the CLKMCU output
        uint8_t clkmcu_freq;    ///> Clock MCU output frequency
        uint8_t clkphy_action;  ///> Enable/Disable the CLKPHY output
    } IfxRfe_setClockOutput_t;

    typedef struct
    {
        uint32_t curr_state;  ///> Current status of the MMIC
    } IfxRfe_getStatusResult_t;

    typedef struct
    {
        uint32_t rom_fw_ver;  ///> Version of ROM Firmware for confirmation.
        uint32_t ram_fw_ver;  ///> Version of the currently running Firmware for confirmation.
        uint32_t auth_data;   ///> Firmware authentication data to allow transition into Low power state.
    } IfxRfe_exitPreOperation_t;

    typedef struct
    {
        uint8_t action;             ///> Action to be performed
        uint16_t error_mask_1;      ///> Error word mask to specify which error of Error Status 1 shall be cleared.
        bool error_mask_1_present;  ///> Flag to indicate whether the field error_mask_1 should be serialized
        uint8_t length;             ///> Number of words in error_mask_2
        uint32_t *error_mask_2;     ///> Error word mask to specify which error of Error Status 2 shall be cleared.
    } IfxRfe_handleError_t;

    typedef struct
    {
        uint8_t failure_ind_m;           ///> There is one or more alarms that triggered failure indication M.
        uint8_t failure_ind_a;           ///> There is one or more alarms that triggered failure indication A.
        uint8_t failure_ind_b;           ///> There is one or more alarms that triggered failure indication B.
        uint8_t failure_ind_c;           ///> There is one or more alarms that triggered failure indication C.
        uint16_t error_status_1;         ///> Each bit in the word represents the status of that corresponding error.
        uint8_t length;                  ///> Number of words in error_status_2
        uint32_t error_status_2[8];      ///> Each bit in the word represents the status of that corresponding error.
        bool optional_fields_available;  ///> Indicates, whether the optional fields were recevied or not
    } IfxRfe_handleErrorResult_t;

    typedef struct
    {
        uint8_t hp;        ///> HP corner frequency.
        uint8_t gain_sel;  ///> RX Chain gain selection.Used to apply a calibrated gain configuration at TIA, LPF, DFE and PF
    } IfxRfe_getRxTfParameters_t;

    typedef struct
    {
        uint16_t rx_temp_t1;             ///> Temperature of the T1 measurement (in Q12.3).
        uint16_t rx_temp_t2;             ///> Temperature of the T2 measurement (in Q12.3).
        uint8_t RX1_HP_MODEL_COEFF_T1;   ///> Deviation from the nominal HP corner freq for RX1 and T1 (in %).
        uint8_t RX2_HP_MODEL_COEFF_T1;   ///> Deviation from the nominal HP corner freq for RX2 and T1 (in %).
        uint8_t RX1_HP_MODEL_COEFF_T2;   ///> Deviation from the nominal HP corner freq for RX1 and T2 (in %).
        uint8_t RX2_HP_MODEL_COEFF_T2;   ///> Deviation from the nominal HP corner freq for RX2 and T2 (in %).
        uint8_t RX3_HP_MODEL_COEFF_T1;   ///> Deviation from the nominal HP corner freq for RX3 and T1 (in %).
        uint8_t RX4_HP_MODEL_COEFF_T1;   ///> Deviation from the nominal HP corner freq for RX4 and T1 (in %).
        uint8_t RX3_HP_MODEL_COEFF_T2;   ///> Deviation from the nominal HP corner freq for RX3 and T2 (in %).
        uint8_t RX4_HP_MODEL_COEFF_T2;   ///> Deviation from the nominal HP corner freq for RX4 and T2 (in %).
        uint8_t RX5_HP_MODEL_COEFF_T1;   ///> Deviation from the nominal HP corner freq for RX5 and T1 (in %).
        uint8_t RX6_HP_MODEL_COEFF_T1;   ///> Deviation from the nominal HP corner freq for RX6 and T1 (in %).
        uint8_t RX5_HP_MODEL_COEFF_T2;   ///> Deviation from the nominal HP corner freq for RX5 and T2 (in %).
        uint8_t RX6_HP_MODEL_COEFF_T2;   ///> Deviation from the nominal HP corner freq for RX6 and T2 (in %).
        uint8_t RX7_HP_MODEL_COEFF_T1;   ///> Deviation from the nominal HP corner freq for RX7 and T1 (in %).
        uint8_t RX8_HP_MODEL_COEFF_T1;   ///> Deviation from the nominal HP corner freq for RX8 and T1 (in %).
        uint8_t RX7_HP_MODEL_COEFF_T2;   ///> Deviation from the nominal HP corner freq for RX7 and T2 (in %).
        uint8_t RX8_HP_MODEL_COEFF_T2;   ///> Deviation from the nominal HP corner freq for RX8 and T2 (in %).
        uint8_t RX1_BBF_MODEL_COEFF_T1;  ///> Deviation from the nominal BBF baseband delay for RX1 and T1 (in %).
        uint8_t RX2_BBF_MODEL_COEFF_T1;  ///> Deviation from the nominal BBF baseband delay for RX2 and T1 (in %).
        uint8_t RX1_BBF_MODEL_COEFF_T2;  ///> Deviation from the nominal BBF baseband delay for RX1 and T2 (in %).
        uint8_t RX2_BBF_MODEL_COEFF_T2;  ///> Deviation from the nominal BBF baseband delay for RX2 and T2 (in %).
        uint8_t RX3_BBF_MODEL_COEFF_T1;  ///> Deviation from the nominal BBF baseband delay for RX3 and T1 (in %).
        uint8_t RX4_BBF_MODEL_COEFF_T1;  ///> Deviation from the nominal BBF baseband delay for RX4 and T1 (in %).
        uint8_t RX3_BBF_MODEL_COEFF_T2;  ///> Deviation from the nominal BBF baseband delay for RX3 and T2 (in %).
        uint8_t RX4_BBF_MODEL_COEFF_T2;  ///> Deviation from the nominal BBF baseband delay for RX4 and T2 (in %).
        uint8_t RX5_BBF_MODEL_COEFF_T1;  ///> Deviation from the nominal BBF baseband delay for RX5 and T1 (in %).
        uint8_t RX6_BBF_MODEL_COEFF_T1;  ///> Deviation from the nominal BBF baseband delay for RX6 and T1 (in %).
        uint8_t RX5_BBF_MODEL_COEFF_T2;  ///> Deviation from the nominal BBF baseband delay for RX5 and T2 (in %).
        uint8_t RX6_BBF_MODEL_COEFF_T2;  ///> Deviation from the nominal BBF baseband delay for RX6 and T2 (in %).
        uint8_t RX7_BBF_MODEL_COEFF_T1;  ///> Deviation from the nominal BBF baseband delay for RX7 and T1 (in %).
        uint8_t RX8_BBF_MODEL_COEFF_T1;  ///> Deviation from the nominal BBF baseband delay for RX8 and T1 (in %).
        uint8_t RX7_BBF_MODEL_COEFF_T2;  ///> Deviation from the nominal BBF baseband delay for RX7 and T2 (in %).
        uint8_t RX8_BBF_MODEL_COEFF_T2;  ///> Deviation from the nominal BBF baseband delay for RX8 and T2 (in %).
    } IfxRfe_getRxTfParametersResult_t;

    typedef struct
    {
        uint32_t wait_time;  ///> Wait time specified in UQ32.0 format having 5 ns resolution. Maximum value is 80 ms.
    } IfxRfe_wait_t;

    typedef struct
    {
        uint8_t action;             ///> Action to be performed
        uint16_t error_mask_1;      ///> Error word mask to specify which error of Error Status 1' shall be cleared.
        bool error_mask_1_present;  ///> Flag to indicate whether the field error_mask_1 should be serialized
        uint8_t length;             ///> Number of words in error_mask_2
        uint32_t *error_mask_2;     ///> Error word mask to specify which error of Error Status 2' shall be cleared.
    } IfxRfe_handleResetReason_t;

    typedef struct
    {
        uint16_t error_status_1;         ///> Each bit in the word represents the status of that corresponding error.
        uint8_t length;                  ///> Number of words in error_status_2
        uint32_t error_status_2[8];      ///> Each bit in the word represents the status of that corresponding error.
        bool optional_fields_available;  ///> Indicates, whether the optional fields were recevied or not
    } IfxRfe_handleResetReasonResult_t;

    typedef struct
    {
        uint8_t length;   ///> Number of command handles to be executed in this batch.
        uint8_t *handle;  ///> Command handle to be executed in this batch.
    } IfxRfe_runBatch_t;

    typedef struct
    {
        uint32_t res_identifier;   ///> Result Identifier of the batch. Call Get_Result() command to get the detail result.
        uint8_t num_succ_handles;  ///> Number of successfully executed command handles.
    } IfxRfe_runBatchResult_t;

    typedef struct
    {
        uint8_t disable_all_tx_pa;  ///> Disable all TX1-4 power amplifiers?
    } IfxRfe_abortRampScenario_t;

    typedef struct
    {
        uint32_t sequencer_run_res;     ///> Sequencer run result (aborted because of errors (based on Sequencer's error registers) or successfully done)
        uint32_t sequencer_dbg_res_id;  ///> Detailed error information based on Sequencer's error registers.
    } IfxRfe_abortRampScenarioResult_t;

    typedef struct
    {
        uint16_t config_mask_ext;       ///> If a pin is selected in the config mask, none of the three settings can be "not selected"
        uint8_t clkmcu_drive_strength;  ///> Select drive strength
        uint8_t clkmcu_driver_config;   ///> Select push-pull or open-drain configuration.
        uint8_t clkmcu_pull_config;     ///> Select tri-state, pull-down or pull-up configuration.
        uint8_t dmux1_drive_strength;   ///> Select drive strength
        uint8_t dmux1_driver_config;    ///> Select push-pull or open-drain configuration.
        uint8_t dmux1_pull_config;      ///> Select tri-state, pull-down or pull-up configuration.
        uint8_t dmux2_drive_strength;   ///> Select drive strength
        uint8_t dmux2_driver_config;    ///> Select push-pull or open-drain configuration.
        uint8_t dmux2_pull_config;      ///> Select tri-state, pull-down or pull-up configuration.
        uint8_t dmux3_drive_strength;   ///> Select drive strength
        uint8_t dmux3_driver_config;    ///> Select push-pull or open-drain configuration.
        uint8_t dmux3_pull_config;      ///> Select tri-state, pull-down or pull-up configuration.
        uint8_t so_drive_strength;      ///> Select drive strength
        uint8_t so_driver_config;       ///> Select push-pull or open-drain configuration.
        uint8_t so_pull_config;         ///> Select tri-state, pull-down or pull-up configuration.
        uint8_t rft_drive_strength;     ///> Select drive strength
        uint8_t rft_driver_config;      ///> Select push-pull or open-drain configuration.
        uint8_t rft_pull_config;        ///> Select tri-state, pull-down or pull-up configuration.
    } IfxRfe_configureDios_t;

    typedef struct
    {
        uint16_t measurement_sub_func_id;  ///> Flags for the measurement routines to be performed:
        uint32_t nmod;                     ///> TX modulator (DPLL) static frequency during measurement.
        uint8_t hp_sel;                    ///> RX Chain HP corner frequency selection for BB measurements.
    } IfxRfe_measureRx_t;

    typedef struct
    {
        uint16_t measurement_sub_func_sum;  ///> Status summary bits for the measurement routines (see request for bit assignments).
        uint32_t res_identifier;            ///> Result Identifier to read measurement data later by Get_Results() command.
    } IfxRfe_measureRxResult_t;

    typedef struct
    {
        uint16_t length;          ///>
        uint16_t offset;          ///>
        uint8_t region;           ///>
        uint32_t res_identifier;  ///>
    } IfxRfe_writeResults_t;

    typedef struct
    {
        uint8_t signal_bit_mask;   ///> Mask of signal bits to set:
        uint8_t signal_bit_value;  ///> Value of signal bits:
    } IfxRfe_setSignals_t;


#ifdef __cplusplus
}  // namespace IfxRfe_Ctrx8188
#endif

#endif  //IFXRFE_CTRXCOMMANDPARAMS_H_8188